### ISSUE TITLE
<footer> of letters

### ISSUE THREAD

**Issue by michael-77** [mgbennet/booker-t-washington_up-from-slavery#9]
Rather than 
```
<footer>
	<p epub:type="z3998:valediction">Very sincerely yours,</p>
	<p epub:type="z3998:sender">John Addison Porter,</p>
	<p epub:type="z3998:sender">Secretary to the President.</p>
</footer>
```
our pattern for footers now tends to be
```
<footer>
	<p>Very sincerely yours,</p>
	<p class="signature">John Addison Porter,<br/>
	Secretary to the President.</p>
</footer>
```
which is simpler to style
```
footer{
	text-align: right;
}
.signature{
	font-variant: small-caps;
}
```
I would just leave the valedictions to the right as they aren't actually centred in the printed edition anyway.

Setting up the styles like this means you also get a gain in `introduction.xhtml` as you can now use 
```
<footer>
	<p class="signature">Walter <abbr class="name">H.</abbr> Page.</p>
</footer>
```
which is neater and allows you to drop some extra css.

For the weird chapter 17 letter - I would either move the recipient block to the top in an editorial commit which would make it much easier to read and make sense of, or you could move it out of the footer and use 
```
footer+p{
	text-indent: 0;
}
```
to style it. My preference would be the former.

**Comment by mgbennet** [comment]
The simpler markup works with me, though I don't see the point in dropping the valediction semantic typing when it's already there.

In the printed edition the valedictions seem to generally be positioned based on the length of the signature, with the exception of the 2nd letter of chapter 16 where they compressed it into the same line as the last paragraph in order to deal with the end of the page. This isn't really a reasonable thing to do with CSS so I approximated it with center alignment, and I think I'd like to keep it centered. If you have strong feelings about it though I can oblige.

The chapter 17 recipient is definitely weird. I'll move it to the header as you suggest. Though the earlier change to move the "To" out of the text marked up as "z3998:recipient" makes aligning it to the left to be consistent with the rest of the letters rather annoying...

**Comment by michael-77** [comment]
I don't have strong preferences about the positioning. It can be very hard to tell the rationale from just the bare source ;-)
```
#chapter-17 blockquote:nth-of-type(10) header p:last-child
```
would target the To: line if it is within the header

**Comment by michael-77** [comment]
> The simpler markup works with me, though I don't see the point in dropping the valediction semantic typing when it's already there.

Probably not worth removing it but definitely add the `signature` class.

**Comment by mgbennet** [comment]
Cool, this is done, then.
